const express = require("express");
const cors = require("cors");
const { Sequelize } = require("sequelize");
const passport = require("passport");
require("dotenv").config();
require("./passport-config");
const sellerRegistration = require("./routes/seller-registration");
const buyerRegistration = require("./routes/buyer-registration");
const orderInquiry = require("./routes/order-inquiry");
const signIn = require("./routes/sign-in");
const buyerGoogleAuth = require("./routes/buyer-google-auth");
const sellerGoogleAuth = require("./routes/seller.google.auth");
const app = express();
const port = 5000;
app.use(cors({ origin:'http://localhost:5173',credentials:true}));
app.use(express.json());
app.use(passport.initialize());
app.use("/", orderInquiry);
app.use("/seller-registration", sellerRegistration);
app.use("/buyer-registration", buyerRegistration);
app.use("/sign-in", signIn);
app.use("/auth", buyerGoogleAuth);
app.use("/auth", sellerGoogleAuth);
app.listen(port, () => {
  console.log(`Example app listening on port ${port}`);
});
